name: Xlog

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: restore timestamps
        uses: chetan/git-restore-mtime-action@v1

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true

      - name: Install xlog
        run: |
          go install github.com/emad-elsaid/xlog/cmd/xlog@latest

      - name: Build
        run: |
          xlog \
          --build . \
          --sitename "Mohamed Shebl" \
          --index=Home \
          --sitemap.domain=www.mohamedshebl.com \
          --activitypub.domain=www.mohamedshebl.com \
          --activitypub.username=Mohamed \
          --activitypub.summary="I'm Mohamed Shebl a software engineer specializing in backend development using Node.js and Express. With expertise in these technologies, I have a strong foundation in building robust and scalable backend solutions. With proficiency in C/C++, Java, JavaScript, Typescript, SQL/NoSQL, and RESTful APIs, I can effectively design and implement backend systems. Additionally, my experience with Git/GitHub, OOP, UML, Docker, and React allows me to collaborate efficiently and deliver high-quality results" \
          --og.domain=www.mohamedshebl.com \
          --twitter.username=@mohamedhamdii74 \
          --github.repo=https://github.com/Adosh74/Adosh74.github.io \
          --rss.domain=www.mohamedshebl.me \
          --rss.description="I'm Mohamed Shebl a software engineer specializing in backend development using Node.js and Express. With expertise in these technologies, I have a strong foundation in building robust and scalable backend solutions. With proficiency in C/C++, Java, JavaScript, Typescript, SQL/NoSQL, and RESTful APIs, I can effectively design and implement backend systems. Additionally, my experience with Git/GitHub, OOP, UML, Docker, and React allows me to collaborate efficiently and deliver high-quality results"
          rm *.md
          chmod -R 0777 .

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.4
        with:
          path: .

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1